server:
  port: 8081
  servlet:
    context-path: /mi
    jsp:
      init-parameters:
        development: true   # ??jsp??????


spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.101.96.53:3306/medical_insurance?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
# ??mybatis
mybatis:
  mapper-locations: classpath:com/zjlab/visualize/mapper/*.xml
  type-aliases-package: com.zjlab.visualize.bean

# ??????
logging:
  level:
    root: info
    com.zjlab.visualize.mapper: debug  #?????
